version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@angular/language-service"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/forms"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1102.10
    - 0.1102.7
    - 0.1102.8
    - 0.1102.9
  - dependency-name: "@angular/compiler-cli"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/compiler"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.8
    - 11.2.9
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: "@ngrx/component-store"
    versions:
    - 11.1.0
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
